FROM java:8-jdk-alpine
COPY ./target/discovery-service-fm-0.0.1-SNAPSHOT.jar /usr/app/
WORKDIR /usr/app
RUN sh -c 'touch discovery-service-fm-0.0.1-SNAPSHOT.jar'
ENTRYPOINT [ "java", "-jar", "discovery-service-fm-0.0.1-SNAPSHOT.jar"]